name: Build and Push Docker Image

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up version tag
      id: version
      run: |
        # Use the short commit SHA and current date for the version tag
        VERSION=$(date +'%Y%m%d')-$(git rev-parse --short HEAD)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/05-project/05-project-client:latest
          ghcr.io/05-project/05-project-client:${{ env.NEXT_VERSION }}
