name: Build and Push Docker Image

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Bump Version
      id: version
      run: |
        NEW_VERSION=$(npm version patch --no-git-tag-version)
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
        echo "Bumped version to $NEW_VERSION"

    - name: Commit and push version bump
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add package.json package-lock.json
        git commit -m "chore: bump version to ${{ env.NEW_VERSION }}"
        git push origin main
        
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/05-project/05-project-client:latest
          ghcr.io/05-project/05-project-client:${{ env.VERSION }}
          
    - name: Create a new Git tag
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git tag ${{ env.NEW_VERSION }}
        git push origin ${{ env.NEW_VERSION }}
