name: Build and Push Docker Image

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch all tags
      run: git fetch --tags

    - name: Calculate next version
      id: version
      run: |
        TAG=$(git describe --tags --match "v[0-9]*" --abbrev=0 2>/dev/null || echo "v0.0.0")
        echo "Latest tag: $TAG"
        VERSION=$(echo $TAG | sed 's/v//')
        IFS='.' read -ra PARTS <<< "$VERSION"
        MAJOR=${PARTS[0]}
        MINOR=$((PARTS[1] + 1))
        NEXT_VERSION="${MAJOR}.${MINOR}.0"
        echo "NEXT_VERSION=v$NEXT_VERSION" >> $GITHUB_ENV
        echo "Next version: v$NEXT_VERSION"
        
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/05-project/05-project-client:latest
          ghcr.io/05-project/05-project-client:${{ env.NEXT_VERSION }}
          
    - name: Create a new Git tag
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git tag v${{ env.NEXT_VERSION }}
        git push origin v${{ env.NEXT_VERSION }}
